name: Environment Variables
on: [workflow_dispatch]

jobs:
  build:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Script.ps1
        run: ./script.ps1
        shell: pwsh
        env:
          MyVariable: 'Hello World'
